### ISSUE TITLE
Problème tarifs En relais Pickup toujours zéro

### ISSUE THREAD

**Issue by HayetJA** [quadra-informatique/SoColissimo-3.x-Prestashop#27]
Bonjour,

Je suis sur prestashop 1.6.1.7 et j'ai installé le module Colissimo Simplicité 3.0.3, j'ai bien configuré le module côté prestashop et les deux transporteurs correspondants.
Par contre j'ai un soucis, côté site, le transporteur colissimo m'affiche toujours à partir de 0 €, les tarifs pour la poste sont bien récupérées mais pas les tarifs du transporteur à proximité, en relais pickup j'ai toujours 0€.
Avez-vous une idée sur la source de ce problème, c'est très urgent.
Merci d'avance pour votre réponse.
![coli](https://cloud.githubusercontent.com/assets/25814224/23012448/994ac0a8-f426-11e6-89a2-30fbcbbbf797.jpg)

**Comment by quadrateam** [comment]
Bonjour,

Avez-vous vérifié la pertinence des données entrées dans votre transporteur en commerce de proximité ? Il y a peut-être une erreur dans les prix renseignés, ou alors vous êtes peut-être dans le cas d'un comportement hors tranche.

Par ailleurs dans le paramétrage du module, avez-vous coché la tarification différente pour la livraison en point de retrait ? 

Cordialement.

**Comment by HayetJA** [comment]
Oui j'ai bien saisie les tarifs pour le transporteur en commerce de proximité, j'ai récupéré les prix depuis la page 2 du pdf en ligne : https://www.colissimo.entreprise.laposte.fr/fr/system/files/imagescontent/docs/TARIF-2017-PRIVILEGE-FR.pdf

Dans le cas de comportement hors tranche j'ai bien sélectionné au niveau du transporteur "Prendre la tranche la plus grande" mais déjà je suis bien dans la deuxième tranche pour cela j'ai 7.41euro pour la poste.

Au niveau du module, j'ai bien choisit la tarification différente et j'ai sélectionné le transporteur en question.

![coli2](https://cloud.githubusercontent.com/assets/25814224/23014949/55f3e0ae-f431-11e6-8304-b4ac4ffcef1c.jpg)

**Comment by HayetJA** [comment]
Bonjour,
Avez-vous une réponse à ma demande svp?

**Comment by quadrateam** [comment]
Bonjour,

Vous avez deux solutions pour corriger ce problème : 
- Vous allez au bout de votre commande et vous faites une nouvelle commande pour créer un nouveau panier et vous regardez si l'erreur persiste,
- Ou vous récupérez l'id de votre panier et supprimez la ligne correspondante à cet id dans la table "ps_socolissimo_delivery_info".

Votre erreur est peut-être dû au fait d'un retour dans la commande. Si vous avez changé les tarifs de votre transporteur alors que votre panier était encore actif, cette erreur peut subvenir.

Cordialement.
