### ISSUE TITLE
Soucis sous android

### ISSUE THREAD

**Issue by digitalplayer** [quadra-informatique/SoColissimo-3.x-Prestashop#29]
J'ai un soucis avec Chrome sous Android, le module ne fonctionne pas (Prestashop 1.6).
Il est bien configuré et fonctionne sur les autres interfaces.

Sur Chrome Android, il va sur l'interface puis revient sur le site et affiche les erreurs visibles sur la PJ.
![img_0942](https://user-images.githubusercontent.com/29796499/27733008-42dd4d30-5d94-11e7-8a70-65625ba201f8.JPG)

**Comment by quadrateam** [comment]
Bonjour,

Ce souci provient d'une configuration manquante ou mal saisie sur la partie mobile dans votre espace colisPoste :  https://www.colissimo.entreprise.laposte.fr/

Bien cordialement,
