### ISSUE TITLE
Module Prestashop mouline depuis hier

### ISSUE THREAD

**Issue by DellortoFR** [quadra-informatique/SoColissimo-3.x-Prestashop#30]
Bonjour,
Gros problème depuis (apparemment) hier avec le module Socolissimo. Pour une livraison à domicile, pas de problème. Mais dès que l'internaute choisi une livraison en point relais, le module semble alors chercher les points environnants, et ne les trouve jamais...
Ca mouline tant qu'on interrompt pas soi-même.
Merci de bien vouloir corriger ce problème, nous avons déjà plusieurs plaintes de clients.
Cordialement

**Comment by quadrateam** [comment]
Bonjour,

Le module appelle une api de choix de point de livraison gérée par la poste. Il arrive parfois que celle ci soit lente ou indisponible. Cela a du être votre cas. Malheureusement quand cela arrive nous n'avons pas la main pour intervenir car cette partie est gérée coté poste.

Bien cordialement,
