### ISSUE TITLE
erreur mise à jour tarifs / mode livraison

### ISSUE THREAD

**Issue by boukhis** [quadra-informatique/SoColissimo-3.x-Prestashop#32]
Module soColissimo 3.0.8 sur Prestashop 1.6.1.0 : Problème tordu :)

La mise à jour du type de livraison et du tarif ne s'effectue pas toujours bien; Suivez mes explications.

information de base : 2 modules de transport soColissimo à 10€ et retrait au dépot à 0€.

si : vous changez de transporteur avant d'aller sur la page de "Paiement" aucun problème tout semble aller (tarifs à 0 ou 10)

si : vous allez sur la page de paiement et retournez après sur la page de livraison et changez pour mettre Colissimo, les anciennes informations de livraison sont conservées (0€ et retrait au dépot)

Voila c'est fini !

**Comment by quadrateam** [comment]
Bonjour,

Il me semble que nous vous avons répondu sur addons sur ce problème. Cela semblait venir du module mondial relais installé en parallèle non ?

Bien cordialement,
