### ISSUE TITLE
Link between carrier and module are delete

### ISSUE THREAD

**Issue by camlafit** [quadra-informatique/SoColissimo-3.x-Prestashop#33]
Hello

When we update configuration from module page , All  all external_module data related to each carrier are deleted.

https://github.com/quadra-informatique/SoColissimo-3.x-Prestashop/blob/master/socolissimo.php#L2044
This method check only socolissimo status not other carrier module

**Comment by quadrateam** [comment]
Hi camlafit ,

Thanks for your contribution, your fix will be included in next release early 2018.

regards
